name: Hardhat CI

on:
  # jalan otomatis saat push / PR ke main
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # jalan manual
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Hardhat tests
        run: npx hardhat test
